### ISSUE TITLE
Edge: Unable to get property "hasOwnProperty"

### ISSUE THREAD

**Issue by lbergman** [mohayonao/stereo-panner-node#11]
When using the polyfill with MS Edge, I get the following error:
Unable to get property "hasOwnProperty" of undefined or null reference.

Seems like BaseAudioContext.prototype on line 96 is undefined in Edge.

**Comment by lbergman** [comment]
Seems like the issue is in base-audio-context.

Modified the last line of base-audio-context index.js to this, and now it seems to work:
module.exports = typeof BaseAudioContext === "function" && BaseAudioContext.prototype ? BaseAudioContext : AudioContext;

**Comment by mohayonao** [comment]
This issue is fixed. thanks! 🍺
