### ISSUE TITLE
No sound in the latest Safari when panning is 0

### ISSUE THREAD

**Issue by aquilax** [mohayonao/stereo-panner-node#13]
In the latest Safari, when the gain's value is 0, the node is muted most likely related to this commit: https://github.com/WebKit/webkit/commit/5990792af4c32822a30a997b23c331aa561d27a2
This causes the panner to be muted when `0` is passed as panning value.

Tested on IOS 11

**Comment by mohayonao** [comment]
Thanks for your report. I've fixed this issue and publish v1.3.3.

**Comment by aquilax** [comment]
We tested on iPhone and iPad and can confirm that the issue is fixed :+1: 

Thanks for the quick reaction!
