### ISSUE TITLE
Breaks in Chrome

### ISSUE THREAD

**Issue by acarabott** [mohayonao/stereo-panner-node#18]
I think there was a recent change in Chrome that breaks this:

An error is thrown about `splitter.channelInterpretation = "speakers";` because `channelInterpretation` cannot be changed from `"discrete"` (as per the [WebAudio API](https://webaudio.github.io/web-audio-api/#the-channelsplitternode-interface).

(this still works in Safari, which is the only place this shim is needed).

This code shouldn't be run in Chrome because there is a check if `createStereoPanner` already exists on the `AudioContext` unfortunately now `AudioContext.prototype.hasOwnProperty("createStereoPanner")` returns `false` so `!("createStereoPanner" in AudioContext.prototype)` must be used.

I'm going to submit a pull request now...

**Comment by acarabott** [comment]
Pull request: #19

**Comment by mohayonao** [comment]
I merged it. Thanks!!! 👍
